import type { CategorySlug } from './categories'

/**
 * Central tool registry — the single source of truth for every tool.
 * Each entry drives the homepage grid, category pages, sidebar nav,
 * ⌘K command-palette search, and per-page SEO.
 *
 * Adding a tool = one entry here + its page file at
 * `app/pages/<category>/<slug>.vue`.
 */

/** Where processing happens: 🟢 client · 🟡 server · 🔵 hybrid. */
export type ProcessingTag = 'client' | 'server' | 'hybrid'

/** `live` = page exists and works. `planned` = registered but not built yet. */
export type ToolStatus = 'live' | 'planned'

/**
 * What a tool must fetch before it can run, beyond the precached app shell.
 * Deliberately separate from `tag`: that says *where* processing happens, which
 * isn't the same question as whether the tool works with no connection.
 *
 * Omitted (the common case) = works offline the moment the shell is cached.
 *
 *   • `network`     — every run needs a live server round-trip; never offline.
 *   • `ffmpeg-core` — the ~31 MB wasm core. Too big to precache, so the service
 *                     worker caches it on first use; offline-capable after that.
 *   • `ml-model`    — segmentation weights fetched from a CDN on first use.
 */
export type ToolRequirement = 'network' | 'ffmpeg-core' | 'ml-model'

export interface Tool {
  /** Globally unique id, also used as a stable key. */
  id: string
  title: string
  category: CategorySlug
  /** Path segment within the category, e.g. `temperature`. */
  slug: string
  tag: ProcessingTag
  description: string
  /** Extra search terms for ⌘K (title/description are always searched). */
  keywords: string[]
  status: ToolStatus
  /** Runtime dependency that affects offline availability. See ToolRequirement. */
  requires?: ToolRequirement
}

export const tools: Tool[] = [
  {
    id: 'temperature',
    title: 'Temperature Converter',
    category: 'convert',
    slug: 'temperature',
    tag: 'client',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin.',
    keywords: ['celsius', 'fahrenheit', 'kelvin', 'c to f', 'degrees'],
    status: 'live',
  },
  {
    id: 'length',
    title: 'Length Converter',
    category: 'convert',
    slug: 'length',
    tag: 'client',
    description: 'Convert between meters, feet, miles, inches, and more.',
    keywords: ['distance', 'meters', 'feet', 'miles', 'inches', 'km'],
    status: 'live',
  },
  {
    id: 'weight',
    title: 'Weight Converter',
    category: 'convert',
    slug: 'weight',
    tag: 'client',
    description: 'Convert between kilograms, pounds, ounces, and grams.',
    keywords: ['mass', 'kg', 'pounds', 'lbs', 'ounces', 'grams'],
    status: 'live',
  },
  {
    id: 'volume',
    title: 'Volume Converter',
    category: 'convert',
    slug: 'volume',
    tag: 'client',
    description: 'Convert between litres, millilitres, gallons, cups, and more.',
    keywords: ['litres', 'liters', 'ml', 'gallons', 'cups', 'pints', 'quarts', 'fluid ounce'],
    status: 'live',
  },
  {
    id: 'area',
    title: 'Area Converter',
    category: 'convert',
    slug: 'area',
    tag: 'client',
    description: 'Convert between square metres, acres, hectares, square feet, and more.',
    keywords: ['square metre', 'acre', 'hectare', 'square feet', 'sq ft', 'land'],
    status: 'live',
  },
  {
    id: 'speed',
    title: 'Speed Converter',
    category: 'convert',
    slug: 'speed',
    tag: 'client',
    description: 'Convert between km/h, mph, m/s, knots, and feet per second.',
    keywords: ['velocity', 'kmh', 'mph', 'knots', 'meters per second', 'ft/s'],
    status: 'live',
  },
  {
    id: 'time',
    title: 'Time Converter',
    category: 'convert',
    slug: 'time',
    tag: 'client',
    description: 'Convert between seconds, minutes, hours, days, weeks, and years.',
    keywords: ['duration', 'seconds', 'minutes', 'hours', 'days', 'weeks', 'months', 'years'],
    status: 'live',
  },
  {
    id: 'data-storage',
    title: 'Data Storage Converter',
    category: 'convert',
    slug: 'data-storage',
    tag: 'client',
    description: 'Convert between bytes, KB, MB, GB, and TB.',
    keywords: ['bytes', 'kilobytes', 'megabytes', 'gigabytes', 'file size'],
    status: 'live',
  },
  {
    id: 'number-base',
    title: 'Number Base Converter',
    category: 'convert',
    slug: 'number-base',
    tag: 'client',
    description: 'Convert between binary, octal, decimal, and hexadecimal.',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'radix'],
    status: 'live',
  },
  {
    id: 'roman-numeral',
    title: 'Roman Numeral Converter',
    category: 'convert',
    slug: 'roman-numeral',
    tag: 'client',
    description: 'Convert numbers to Roman numerals and back (1–3999).',
    keywords: ['roman', 'numeral', 'mmxxiv', 'latin numbers'],
    status: 'live',
  },
  {
    id: 'timezone',
    title: 'Timezone Converter',
    category: 'convert',
    slug: 'timezone',
    tag: 'client',
    description: 'Convert a date and time between world time zones.',
    keywords: ['timezone', 'time zone', 'utc', 'gmt', 'world clock'],
    status: 'live',
  },
  {
    id: 'currency',
    title: 'Currency Converter',
    category: 'convert',
    slug: 'currency',
    tag: 'server',
    description: 'Convert between world currencies at recent exchange rates.',
    keywords: ['currency', 'money', 'exchange rate', 'forex', 'usd', 'eur'],
    status: 'live',
    requires: 'network',
  },
  {
    id: 'image-watermark',
    title: 'Add Watermark',
    category: 'image',
    slug: 'watermark',
    tag: 'client',
    description: 'Overlay text watermarks on an image, with position and opacity control.',
    keywords: ['watermark', 'text overlay', 'copyright', 'stamp', 'brand'],
    status: 'live',
  },
  {
    id: 'image-resize',
    title: 'Resize Image',
    category: 'image',
    slug: 'resize',
    tag: 'client',
    description: 'Resize or scale an image by pixels or percentage, keeping aspect ratio.',
    keywords: ['resize', 'scale', 'dimensions', 'width', 'height', 'shrink', 'enlarge'],
    status: 'live',
  },
  {
    id: 'image-convert',
    title: 'Image Format Converter',
    category: 'image',
    slug: 'convert',
    tag: 'client',
    description: 'Convert images between PNG, JPG, WebP, and AVIF.',
    keywords: ['convert', 'png', 'jpg', 'jpeg', 'webp', 'avif', 'format'],
    status: 'live',
  },
  {
    id: 'image-compress',
    title: 'Compress Image',
    category: 'image',
    slug: 'compress',
    tag: 'client',
    description: 'Shrink image file size with an adjustable quality slider.',
    keywords: ['compress', 'optimize', 'reduce size', 'quality', 'shrink'],
    status: 'live',
  },
  {
    id: 'image-crop',
    title: 'Crop Image',
    category: 'image',
    slug: 'crop',
    tag: 'client',
    description: 'Crop an image to a custom rectangle by dragging on the preview.',
    keywords: ['crop', 'trim', 'cut', 'rectangle', 'selection'],
    status: 'live',
  },
  {
    id: 'image-rotate',
    title: 'Rotate & Flip Image',
    category: 'image',
    slug: 'rotate',
    tag: 'client',
    description: 'Rotate an image in 90° steps and flip it horizontally or vertically.',
    keywords: ['rotate', 'flip', 'mirror', 'turn', 'orientation'],
    status: 'live',
  },
  {
    id: 'image-color-picker',
    title: 'Image Color Picker',
    category: 'image',
    slug: 'color-picker',
    tag: 'client',
    description: 'Pick colors from an image and read them as HEX, RGB, and HSL.',
    keywords: ['color picker', 'eyedropper', 'hex', 'rgb', 'hsl', 'sample'],
    status: 'live',
  },
  {
    id: 'image-base64',
    title: 'Image ↔ Base64',
    category: 'image',
    slug: 'base64',
    tag: 'client',
    description: 'Encode an image to a Base64 data URL, or decode one back to an image.',
    keywords: ['base64', 'data url', 'encode', 'decode', 'inline image'],
    status: 'live',
  },
  {
    id: 'image-favicon',
    title: 'Favicon Generator',
    category: 'image',
    slug: 'favicon',
    tag: 'client',
    description: 'Generate favicon PNGs and an .ico from a single source image.',
    keywords: ['favicon', 'ico', 'icon', 'app icon', 'apple touch'],
    status: 'live',
  },
  {
    id: 'image-meme',
    title: 'Meme Generator',
    category: 'image',
    slug: 'meme',
    tag: 'client',
    description: 'Add classic top and bottom captions to an image.',
    keywords: ['meme', 'caption', 'impact', 'top text', 'bottom text'],
    status: 'live',
  },
  {
    id: 'image-heic-to-jpg',
    title: 'HEIC to JPG',
    category: 'image',
    slug: 'heic-to-jpg',
    tag: 'hybrid',
    description: 'Convert Apple HEIC/HEIF photos to JPG, entirely in your browser.',
    keywords: ['heic', 'heif', 'apple', 'iphone photo', 'jpg', 'convert'],
    status: 'live',
  },
  {
    id: 'image-remove-bg',
    title: 'Remove Background',
    category: 'image',
    slug: 'remove-bg',
    tag: 'hybrid',
    description: 'Cut out the background from an image to make it transparent.',
    keywords: ['remove background', 'transparent', 'cutout', 'subject', 'png'],
    status: 'live',
    requires: 'ml-model',
  },
  {
    id: 'pdf-merge',
    title: 'Merge PDFs',
    category: 'pdf',
    slug: 'merge',
    tag: 'client',
    description: 'Combine several PDF files into one, in any order you like.',
    keywords: ['merge', 'combine', 'join', 'concat', 'append'],
    status: 'live',
  },
  {
    id: 'pdf-split',
    title: 'Split PDF',
    category: 'pdf',
    slug: 'split',
    tag: 'client',
    description: 'Extract page ranges or split a PDF into multiple documents.',
    keywords: ['split', 'extract pages', 'divide', 'separate', 'page range'],
    status: 'live',
  },
  {
    id: 'pdf-images-to-pdf',
    title: 'Images to PDF',
    category: 'pdf',
    slug: 'images-to-pdf',
    tag: 'client',
    description: 'Combine JPG and PNG images into a single PDF document.',
    keywords: ['images to pdf', 'jpg to pdf', 'png to pdf', 'photos', 'convert'],
    status: 'live',
  },
  {
    id: 'pdf-to-images',
    title: 'PDF to Images',
    category: 'pdf',
    slug: 'to-images',
    tag: 'client',
    description: 'Render each page of a PDF to a PNG or JPG image.',
    keywords: ['pdf to images', 'pdf to png', 'pdf to jpg', 'render', 'export pages'],
    status: 'live',
  },
  {
    id: 'pdf-organize',
    title: 'Organize Pages',
    category: 'pdf',
    slug: 'organize',
    tag: 'client',
    description: 'Reorder and delete pages with a visual page thumbnail grid.',
    keywords: ['organize', 'reorder', 'delete pages', 'rearrange', 'remove page'],
    status: 'live',
  },
  {
    id: 'pdf-rotate',
    title: 'Rotate PDF Pages',
    category: 'pdf',
    slug: 'rotate',
    tag: 'client',
    description: 'Rotate some or all pages of a PDF in 90° steps.',
    keywords: ['rotate', 'turn', 'landscape', 'portrait', 'orientation'],
    status: 'live',
  },
  {
    id: 'pdf-watermark',
    title: 'Watermark PDF',
    category: 'pdf',
    slug: 'watermark',
    tag: 'client',
    description: 'Stamp a text watermark across every page of a PDF.',
    keywords: ['watermark', 'stamp', 'confidential', 'draft', 'overlay'],
    status: 'live',
  },
  {
    id: 'pdf-protect',
    title: 'Protect PDF',
    category: 'pdf',
    slug: 'protect',
    tag: 'client',
    description: 'Add a password to encrypt and protect a PDF.',
    keywords: ['protect', 'encrypt', 'password', 'secure', 'lock'],
    status: 'live',
  },
  {
    id: 'pdf-unlock',
    title: 'Unlock PDF',
    category: 'pdf',
    slug: 'unlock',
    tag: 'client',
    description: 'Remove the password from a PDF you can already open.',
    keywords: ['unlock', 'decrypt', 'remove password', 'unprotect'],
    status: 'live',
  },
  {
    id: 'pdf-extract-text',
    title: 'Extract Text from PDF',
    category: 'pdf',
    slug: 'extract-text',
    tag: 'hybrid',
    description: 'Pull the selectable text out of a PDF, page by page.',
    keywords: ['extract text', 'pdf to text', 'copy text', 'ocr', 'read'],
    status: 'live',
  },
  {
    id: 'pdf-compress',
    title: 'Compress PDF',
    category: 'pdf',
    slug: 'compress',
    tag: 'hybrid',
    description: 'Reduce the file size of a PDF document.',
    keywords: ['compress', 'reduce size', 'optimize', 'shrink'],
    status: 'live',
  },
  {
    id: 'pdf-office-to-pdf',
    title: 'Word to PDF',
    category: 'pdf',
    slug: 'office-to-pdf',
    tag: 'client',
    description: 'Convert Word (.docx) documents to PDF, entirely in your browser.',
    keywords: ['office to pdf', 'word to pdf', 'docx', 'doc', 'document'],
    status: 'live',
  },
  {
    id: 'text-counter',
    title: 'Word & Character Counter',
    category: 'text',
    slug: 'counter',
    tag: 'client',
    description: 'Count words, characters, sentences, and reading time as you type.',
    keywords: ['word count', 'character count', 'letters', 'sentences', 'reading time'],
    status: 'live',
  },
  {
    id: 'text-case',
    title: 'Case Converter',
    category: 'text',
    slug: 'case',
    tag: 'client',
    description: 'Convert text between UPPER, lower, Title, camelCase, snake_case, and more.',
    keywords: ['uppercase', 'lowercase', 'title case', 'camelcase', 'snake case', 'kebab'],
    status: 'live',
  },
  {
    id: 'text-find-replace',
    title: 'Find & Replace',
    category: 'text',
    slug: 'find-replace',
    tag: 'client',
    description: 'Find and replace text with plain or regular-expression matching.',
    keywords: ['find replace', 'regex', 'substitute', 'search', 'pattern'],
    status: 'live',
  },
  {
    id: 'text-lines',
    title: 'Sort & Dedupe Lines',
    category: 'text',
    slug: 'lines',
    tag: 'client',
    description: 'Sort, reverse, shuffle, trim, and remove duplicate or empty lines.',
    keywords: ['sort lines', 'dedupe', 'duplicate', 'unique', 'reverse', 'shuffle'],
    status: 'live',
  },
  {
    id: 'text-lorem-ipsum',
    title: 'Lorem Ipsum Generator',
    category: 'text',
    slug: 'lorem-ipsum',
    tag: 'client',
    description: 'Generate placeholder paragraphs, sentences, or words of lorem ipsum.',
    keywords: ['lorem ipsum', 'placeholder', 'dummy text', 'filler'],
    status: 'live',
  },
  {
    id: 'text-diff',
    title: 'Text Diff',
    category: 'text',
    slug: 'diff',
    tag: 'client',
    description: 'Compare two blocks of text and highlight added and removed lines.',
    keywords: ['diff', 'compare', 'difference', 'changes', 'merge'],
    status: 'live',
  },
  {
    id: 'text-slug',
    title: 'Slug Generator',
    category: 'text',
    slug: 'slug',
    tag: 'client',
    description: 'Turn any text into a clean, URL-friendly slug.',
    keywords: ['slug', 'slugify', 'url', 'permalink', 'kebab'],
    status: 'live',
  },
  {
    id: 'text-markdown-html',
    title: 'Markdown ↔ HTML',
    category: 'text',
    slug: 'markdown-html',
    tag: 'client',
    description: 'Convert Markdown to HTML and HTML back to Markdown.',
    keywords: ['markdown', 'html', 'md', 'convert', 'render'],
    status: 'live',
  },
  {
    id: 'text-tts',
    title: 'Text to Speech',
    category: 'text',
    slug: 'tts',
    tag: 'client',
    description: 'Read text aloud with your browser’s built-in speech voices.',
    keywords: ['text to speech', 'tts', 'speak', 'voice', 'read aloud'],
    status: 'live',
  },
  {
    id: 'base64',
    title: 'Base64 Encode / Decode',
    category: 'encode',
    slug: 'base64',
    tag: 'client',
    description: 'Encode text to Base64 or decode Base64 back to text.',
    keywords: ['base64', 'encode', 'decode', 'atob', 'btoa'],
    status: 'live',
  },
  {
    id: 'encode-url',
    title: 'URL Encode / Decode',
    category: 'encode',
    slug: 'url',
    tag: 'client',
    description: 'Percent-encode text for URLs or decode it back to plain text.',
    keywords: ['url encode', 'percent encoding', 'uri', 'escape', 'decode'],
    status: 'live',
  },
  {
    id: 'encode-json',
    title: 'JSON Formatter',
    category: 'encode',
    slug: 'json',
    tag: 'client',
    description: 'Format, validate, and minify JSON with clear error messages.',
    keywords: ['json', 'format', 'beautify', 'minify', 'validate', 'pretty print'],
    status: 'live',
  },
  {
    id: 'encode-xml-yaml',
    title: 'XML & YAML Formatter',
    category: 'encode',
    slug: 'xml-yaml',
    tag: 'client',
    description: 'Pretty-print XML and convert between YAML and JSON.',
    keywords: ['xml', 'yaml', 'format', 'beautify', 'yaml to json', 'json to yaml'],
    status: 'live',
  },
  {
    id: 'encode-html',
    title: 'HTML Encode / Decode',
    category: 'encode',
    slug: 'html',
    tag: 'client',
    description: 'Escape text to HTML entities or decode entities back to text.',
    keywords: ['html encode', 'entities', 'escape', 'unescape', 'amp'],
    status: 'live',
  },
  {
    id: 'encode-jwt',
    title: 'JWT Decoder',
    category: 'encode',
    slug: 'jwt',
    tag: 'client',
    description: 'Decode a JSON Web Token’s header and payload without a key.',
    keywords: ['jwt', 'json web token', 'decode', 'bearer', 'claims'],
    status: 'live',
  },
  {
    id: 'encode-csv-json',
    title: 'CSV ↔ JSON',
    category: 'encode',
    slug: 'csv-json',
    tag: 'client',
    description: 'Convert CSV to a JSON array and JSON back to CSV.',
    keywords: ['csv', 'json', 'convert', 'spreadsheet', 'table'],
    status: 'live',
  },
  {
    id: 'encode-hash',
    title: 'Hash Generator',
    category: 'encode',
    slug: 'hash',
    tag: 'client',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes of text.',
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'sha512', 'checksum', 'digest'],
    status: 'live',
  },
  {
    id: 'uuid',
    title: 'UUID Generator',
    category: 'encode',
    slug: 'uuid',
    tag: 'client',
    description: 'Generate random RFC 4122 v4 UUIDs, one or many at a time.',
    keywords: ['uuid', 'guid', 'unique id', 'random', 'v4'],
    status: 'live',
  },
  {
    id: 'generate-qr-code',
    title: 'QR Code Generator',
    category: 'generate',
    slug: 'qr-code',
    tag: 'client',
    description: 'Create a QR code from any text or URL and download it as PNG or SVG.',
    keywords: ['qr code', 'qrcode', 'generate', 'url', 'wifi', 'barcode'],
    status: 'live',
  },
  {
    id: 'generate-password',
    title: 'Password Generator',
    category: 'generate',
    slug: 'password',
    tag: 'client',
    description: 'Generate strong, random passwords with adjustable length and character sets.',
    keywords: ['password', 'passphrase', 'random', 'secure', 'strong', 'generator'],
    status: 'live',
  },
  {
    id: 'generate-qr-scanner',
    title: 'QR & Barcode Scanner',
    category: 'generate',
    slug: 'qr-scanner',
    tag: 'client',
    description: 'Scan a QR code or barcode from an image or your camera.',
    keywords: ['qr scanner', 'barcode', 'scan', 'read qr', 'decode', 'camera'],
    status: 'live',
  },
  {
    id: 'generate-palette',
    title: 'Color Palette Generator',
    category: 'generate',
    slug: 'palette',
    tag: 'client',
    description: 'Build harmonious color palettes and CSS gradients from a base color.',
    keywords: ['palette', 'colors', 'gradient', 'scheme', 'complementary', 'analogous'],
    status: 'live',
  },
  {
    id: 'generate-random',
    title: 'Random Number & Picker',
    category: 'generate',
    slug: 'random',
    tag: 'client',
    description: 'Roll dice, flip coins, pick from a list, or generate random numbers.',
    keywords: ['random', 'number', 'dice', 'coin', 'picker', 'shuffle', 'lottery'],
    status: 'live',
  },
  {
    id: 'generate-placeholder',
    title: 'Placeholder Image Generator',
    category: 'generate',
    slug: 'placeholder',
    tag: 'client',
    description: 'Generate solid placeholder images with custom size, colors, and label.',
    keywords: ['placeholder', 'image', 'dummy', 'mockup', 'svg', 'png'],
    status: 'live',
  },
  {
    id: 'color-convert',
    title: 'HEX ↔ RGB ↔ HSL',
    category: 'color',
    slug: 'convert',
    tag: 'client',
    description: 'Convert colors between HEX, RGB, and HSL notations.',
    keywords: ['hex', 'rgb', 'hsl', 'color convert', 'color code'],
    status: 'live',
  },
  {
    id: 'color-contrast',
    title: 'Contrast Checker',
    category: 'color',
    slug: 'contrast',
    tag: 'client',
    description: 'Check color contrast ratios against WCAG AA and AAA accessibility levels.',
    keywords: ['contrast', 'accessibility', 'wcag', 'a11y', 'ratio', 'readable'],
    status: 'live',
  },
  {
    id: 'color-css-generator',
    title: 'Shadow & Gradient CSS',
    category: 'color',
    slug: 'css-generator',
    tag: 'client',
    description: 'Generate box-shadow and CSS gradient code with a live preview.',
    keywords: ['box shadow', 'gradient', 'css', 'generator', 'linear', 'radial'],
    status: 'live',
  },
  {
    id: 'media-convert',
    title: 'Audio & Video Converter',
    category: 'media',
    slug: 'convert',
    tag: 'hybrid',
    description: 'Convert video and audio between MP4, WebM, MP3, WAV, and more in your browser.',
    keywords: ['video', 'audio', 'convert', 'mp4', 'webm', 'mp3', 'wav', 'transcode', 'ffmpeg'],
    status: 'live',
    requires: 'ffmpeg-core',
  },
  {
    id: 'media-trim',
    title: 'Trim Audio & Video',
    category: 'media',
    slug: 'trim',
    tag: 'hybrid',
    description: 'Cut a clip out of a video or audio file without uploading it anywhere.',
    keywords: ['trim', 'cut', 'clip', 'crop video', 'shorten', 'split', 'ffmpeg'],
    status: 'live',
    requires: 'ffmpeg-core',
  },
  {
    id: 'media-extract-audio',
    title: 'Extract Audio from Video',
    category: 'media',
    slug: 'extract-audio',
    tag: 'hybrid',
    description: 'Pull the soundtrack out of a video as MP3, M4A, WAV, or FLAC.',
    keywords: ['extract audio', 'video to mp3', 'rip audio', 'soundtrack', 'mp3', 'ffmpeg'],
    status: 'live',
    requires: 'ffmpeg-core',
  },
  {
    id: 'media-gif',
    title: 'Video to GIF',
    category: 'media',
    slug: 'gif',
    tag: 'hybrid',
    description: 'Turn a section of a video into an animated GIF, entirely in your browser.',
    keywords: ['gif', 'animated gif', 'video to gif', 'gif maker', 'ffmpeg'],
    status: 'live',
    requires: 'ffmpeg-core',
  },
  {
    id: 'dev-formatter',
    title: 'Code Formatter',
    category: 'dev',
    slug: 'formatter',
    tag: 'client',
    description: 'Beautify JavaScript, HTML, CSS, JSON, and SQL with adjustable indentation.',
    keywords: ['format', 'beautify', 'prettier', 'code', 'indent', 'pretty print'],
    status: 'live',
  },
  {
    id: 'dev-minifier',
    title: 'Code Minifier',
    category: 'dev',
    slug: 'minifier',
    tag: 'client',
    description: 'Minify JavaScript, CSS, and HTML to reduce file size.',
    keywords: ['minify', 'compress', 'terser', 'csso', 'code', 'shrink', 'uglify'],
    status: 'live',
  },
  {
    id: 'dev-regex',
    title: 'Regex Tester',
    category: 'dev',
    slug: 'regex',
    tag: 'client',
    description:
      'Test a regular expression against sample text with live match highlighting, a match/group breakdown, and a plain-English explanation.',
    keywords: ['regex', 'regexp', 'regular expression', 'pattern', 'match', 'test', 'explain'],
    status: 'live',
  },
  {
    id: 'dev-cron',
    title: 'Cron Expression Tool',
    category: 'dev',
    slug: 'cron',
    tag: 'client',
    description:
      'Build or paste a cron expression, see a plain-English explanation, and preview upcoming run times.',
    keywords: ['cron', 'crontab', 'schedule', 'cronstrue', 'expression', 'explain'],
    status: 'live',
  },
  {
    id: 'dev-diff',
    title: 'Side-by-Side Diff',
    category: 'dev',
    slug: 'diff',
    tag: 'client',
    description:
      'Compare two blocks of code side by side with word-level highlights on changed lines.',
    keywords: [
      'diff',
      'compare',
      'side by side',
      'merge view',
      'code diff',
      'two column',
      'word diff',
    ],
    status: 'live',
  },
  {
    id: 'dev-json-to-ts',
    title: 'JSON to TypeScript',
    category: 'dev',
    slug: 'json-to-ts',
    tag: 'client',
    description: 'Generate TypeScript interfaces from a sample JSON object or array.',
    keywords: ['json', 'typescript', 'interface', 'type', 'codegen', 'dto'],
    status: 'live',
  },
  {
    id: 'dev-http-status',
    title: 'HTTP Status Code Reference',
    category: 'dev',
    slug: 'http-status',
    tag: 'client',
    description: 'Look up HTTP status codes by number, name, or keyword, grouped by class.',
    keywords: ['http', 'status code', 'response code', '404', '500', 'rest api', 'reference'],
    status: 'live',
  },
  {
    id: 'dev-config-generator',
    title: 'Server Config Generator',
    category: 'dev',
    slug: 'config-generator',
    tag: 'client',
    description:
      'Generate an .htaccess or nginx config snippet from common web-server behaviors — HTTPS redirects, caching, CORS, SPA routing, and more.',
    keywords: ['htaccess', 'nginx', 'apache', 'config', 'redirect', 'gzip', 'cors', 'spa'],
    status: 'live',
  },
  {
    id: 'dev-escape',
    title: 'Escape / Unescape',
    category: 'dev',
    slug: 'escape',
    tag: 'client',
    description:
      'Escape or unescape text for JSON string literals, HTML entities, and SQL string literals.',
    keywords: ['escape', 'unescape', 'json', 'html', 'sql', 'string literal', 'quote'],
    status: 'live',
  },
  {
    id: 'network-speed-test',
    title: 'Internet Speed Test',
    category: 'network',
    slug: 'speed-test',
    tag: 'hybrid',
    description: 'Measure your connection’s ping, download, and upload speed.',
    keywords: ['speed test', 'ping', 'download', 'upload', 'bandwidth', 'mbps', 'latency'],
    status: 'live',
    requires: 'network',
  },
  {
    id: 'network-ping',
    title: 'Ping / Latency Check',
    category: 'network',
    slug: 'ping',
    tag: 'hybrid',
    description: 'Check round-trip latency to a hostname or URL.',
    keywords: ['ping', 'latency', 'rtt', 'round trip', 'network check'],
    status: 'live',
    requires: 'network',
  },
]

/** Route path for a tool, e.g. `/convert/temperature`. */
export function toolRoute(tool: Tool): string {
  return `/${tool.category}/${tool.slug}`
}

const toolById = new Map(tools.map((t) => [t.id, t]))

export function getTool(id: string): Tool | undefined {
  return toolById.get(id)
}

export function toolsInCategory(category: CategorySlug): Tool[] {
  return tools.filter((t) => t.category === category)
}
